#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# CyberPanel Security Suite — Installer
# Compatible with CyberPanel 2.4.4+
# Author: S M Mehdi Akram | Royal Technologies (https://royaltechbd.com)
# ═══════════════════════════════════════════════════════════════════════════

set -e

PLUGIN_DIR="/usr/local/CyberCP/plugins/securitysuite"
CYBERPANEL_URLS="/usr/local/CyberCP/CyberCP/urls.py"
SETTINGS_FILE="/usr/local/CyberCP/CyberCP/settings.py"
SIDEBAR_FILE="/usr/local/CyberCP/baseTemplate/templates/baseTemplate/index.html"
REPO_URL="https://github.com/mehdiakram/cyberpanel-security-suite.git"
LOG_FILE="/var/log/securitysuite.log"
MARKER="# SecuritySuite Plugin"
SIDEBAR_MARKER_START="<!-- SecuritySuite Menu Start -->"
SIDEBAR_MARKER_END="<!-- SecuritySuite Menu End -->"

echo "╔══════════════════════════════════════════════╗"
echo "║  CyberPanel Security Suite — Installer       ║"
echo "║  v1.7 | CyberPanel 2.4.4+ Compatible        ║"
echo "║  Royal Technologies (royaltechbd.com)        ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── Preflight checks ──────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
    echo "✗ Error: This script must be run as root."
    exit 1
fi

if [ ! -d "/usr/local/CyberCP" ]; then
    echo "✗ Error: CyberPanel is not installed at /usr/local/CyberCP"
    exit 1
fi

if [ ! -f "$CYBERPANEL_URLS" ]; then
    echo "✗ Error: CyberPanel urls.py not found at $CYBERPANEL_URLS"
    exit 1
fi

# ── Install ipset (for country blocking) ─────────────────────────────────
echo "→ Checking ipset…"
if command -v ipset &> /dev/null; then
    echo "  ✓ ipset is already installed."
else
    echo "  → Installing ipset…"
    if command -v apt &> /dev/null; then
        apt install -y -qq ipset
    elif command -v yum &> /dev/null; then
        yum install -y -q ipset
    elif command -v dnf &> /dev/null; then
        dnf install -y -q ipset
    fi
    if command -v ipset &> /dev/null; then
        echo "  ✓ ipset installed."
    else
        echo "  ⚠ Could not install ipset. Country blocking may not work."
    fi
fi

# ── Install Fail2ban automatically ───────────────────────────────────────
echo "→ Checking Fail2ban…"
if command -v fail2ban-client &> /dev/null; then
    echo "  ✓ Fail2ban is already installed."
else
    echo "  → Installing Fail2ban…"
    if command -v apt &> /dev/null; then
        apt update -qq && apt install -y -qq fail2ban
    elif command -v yum &> /dev/null; then
        yum install -y -q fail2ban
    elif command -v dnf &> /dev/null; then
        dnf install -y -q fail2ban
    fi

    if command -v fail2ban-client &> /dev/null; then
        echo "  ✓ Fail2ban installed successfully."
    else
        echo "  ⚠ Could not install Fail2ban automatically."
        echo "    Install manually: apt install fail2ban -y"
    fi
fi

# Start and enable Fail2ban
echo "→ Starting Fail2ban service…"
systemctl enable fail2ban 2>/dev/null || true
systemctl start fail2ban 2>/dev/null || true
if systemctl is-active --quiet fail2ban; then
    echo "  ✓ Fail2ban is running."
else
    echo "  ⚠ Fail2ban could not be started. Check: systemctl status fail2ban"
fi

# Configure default jails if none exist
echo "→ Checking Fail2ban jail configuration…"
JAIL_COUNT=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | grep -c '[a-z]' 2>/dev/null || echo "0")

if [ "$JAIL_COUNT" -eq 0 ] || [ "$JAIL_COUNT" = "0" ]; then
    echo "  → No jails configured. Creating default jails…"

    # Create jail.local with sensible defaults
    if [ ! -f /etc/fail2ban/jail.local ]; then
        cat > /etc/fail2ban/jail.local << 'JAILEOF'
# ═══════════════════════════════════════════════════════════════
# Fail2ban Jail Configuration
# Auto-generated by CyberPanel Security Suite
# ═══════════════════════════════════════════════════════════════

[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 5
banaction = iptables-multiport

# ── SSH Protection ──────────────────────────────────────────
[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 5
bantime  = 3600

# ── CyberPanel Login Protection ────────────────────────────
[cyberpanel]
enabled  = true
port     = 8090
filter   = cyberpanel
logpath  = /usr/local/lscp/logs/error.log
maxretry = 5
bantime  = 3600

# ── Postfix SMTP Protection ────────────────────────────────
[postfix]
enabled  = true
port     = smtp,465,submission
filter   = postfix
logpath  = /var/log/mail.log
maxretry = 5
bantime  = 3600
JAILEOF
        echo "  ✓ Created /etc/fail2ban/jail.local"
    else
        echo "  ⚠ jail.local exists but no jails active. Check config."
    fi

    # Create CyberPanel filter if not exists
    if [ ! -f /etc/fail2ban/filter.d/cyberpanel.conf ]; then
        cat > /etc/fail2ban/filter.d/cyberpanel.conf << 'FILTEREOF'
[Definition]
failregex = .*Failed login attempt from <HOST>.*
            .*Authentication failure.*client <HOST>.*
ignoreregex =
FILTEREOF
        echo "  ✓ Created CyberPanel filter."
    fi

    # Restart fail2ban to apply new jails
    systemctl restart fail2ban 2>/dev/null || true
    sleep 2

    # Verify jails are now active
    NEW_JAIL_COUNT=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | grep -c '[a-z]' 2>/dev/null || echo "0")
    echo "  ✓ Active jails: $NEW_JAIL_COUNT"
    fail2ban-client status 2>/dev/null | grep "Jail list:" || true
else
    echo "  ✓ $JAIL_COUNT jail(s) already configured."
fi

# ── Install plugin files ─────────────────────────────────────────────────
echo "→ Removing old installation (if exists)…"
rm -rf "$PLUGIN_DIR"

echo "→ Cloning repository…"
git clone "$REPO_URL" /tmp/cyberpanel-security-suite

echo "→ Copying plugin files…"
mkdir -p "$PLUGIN_DIR"
cp -r /tmp/cyberpanel-security-suite/securitysuite/* "$PLUGIN_DIR/"

echo "→ Cleaning up temp files…"
rm -rf /tmp/cyberpanel-security-suite

echo "→ Setting ownership and permissions…"
chown -R root:root "$PLUGIN_DIR"
chmod -R 755 "$PLUGIN_DIR"

echo "→ Creating log file…"
touch "$LOG_FILE"
chmod 644 "$LOG_FILE"

# ── Add plugin to Python path ────────────────────────────────────────────
echo "→ Adding plugin to Python path…"
PLUGINS_DIR="/usr/local/CyberCP/plugins"

for site_dir in /usr/local/CyberCP/lib/python3.*/site-packages/ /usr/local/lib/python3.*/dist-packages/; do
    if [ -d "$site_dir" ]; then
        echo "$PLUGINS_DIR" > "${site_dir}securitysuite.pth"
        echo "  ✓ Created .pth in $site_dir"
        break
    fi
done

if [ ! -f "$PLUGINS_DIR/__init__.py" ]; then
    touch "$PLUGINS_DIR/__init__.py"
fi

# ── Configure sudoers for CyberPanel user ────────────────────────────────
echo "→ Configuring passwordless sudo for CyberPanel user…"
cat > /etc/sudoers.d/cyberpanel-security-suite << 'SUDOEOF'
# Allows CyberPanel to manage Fail2ban securely without password
cyberpanel ALL=(root) NOPASSWD: /usr/bin/fail2ban-client, /usr/local/bin/fail2ban-client, /usr/sbin/fail2ban-client, /usr/bin/tail -n * /var/log/fail2ban.log
SUDOEOF
chmod 0440 /etc/sudoers.d/cyberpanel-security-suite
echo "  ✓ Added /etc/sudoers.d/cyberpanel-security-suite"

# ── Register URL route in CyberPanel ─────────────────────────────────────
echo "→ Registering Security Suite URL route…"

if grep -q "$MARKER" "$CYBERPANEL_URLS" 2>/dev/null; then
    echo "  ✓ URL route already registered. Skipping."
else
    if ! grep -q "from django.urls import.*include" "$CYBERPANEL_URLS" && \
       ! grep -q "from django.conf.urls import include" "$CYBERPANEL_URLS"; then
        sed -i '1s/^/from django.urls import include\n/' "$CYBERPANEL_URLS"
        echo "  ✓ Added 'include' import."
    fi

    if grep -q "urlpatterns" "$CYBERPANEL_URLS"; then
        sed -i "/^urlpatterns/,/\]/ {
            /\]/ i\\    path('securitysuite/', include('securitysuite.urls')),  $MARKER
        }" "$CYBERPANEL_URLS"

        if grep -q "$MARKER" "$CYBERPANEL_URLS"; then
            echo "  ✓ URL route registered successfully."
        else
            echo "" >> "$CYBERPANEL_URLS"
            echo "$MARKER" >> "$CYBERPANEL_URLS"
            echo "urlpatterns += [path('securitysuite/', include('securitysuite.urls'))]" >> "$CYBERPANEL_URLS"
            echo "  ✓ URL route registered (fallback method)."
        fi
    fi
fi

# ── Add to INSTALLED_APPS ────────────────────────────────────────────────
if [ -f "$SETTINGS_FILE" ]; then
    echo "→ Checking INSTALLED_APPS…"
    if grep -q "'securitysuite'" "$SETTINGS_FILE" 2>/dev/null; then
        echo "  ✓ Already in INSTALLED_APPS."
    else
        sed -i "/INSTALLED_APPS/,/\]/ {
            /\]/ i\\    'securitysuite',  $MARKER
        }" "$SETTINGS_FILE"
        if grep -q "'securitysuite'" "$SETTINGS_FILE"; then
            echo "  ✓ Added to INSTALLED_APPS."
        else
            echo "  ⚠ Could not auto-add. Add 'securitysuite' to INSTALLED_APPS manually."
        fi
    fi
fi

# ── Add Security Suite to CyberPanel sidebar via JavaScript ──────────────
echo "→ Adding Security Suite to CyberPanel sidebar…"

if [ -f "$SIDEBAR_FILE" ]; then
    # Remove old injection if exists
    if grep -q "$SIDEBAR_MARKER_START" "$SIDEBAR_FILE"; then
        sed -i "/$SIDEBAR_MARKER_START/,/$SIDEBAR_MARKER_END/d" "$SIDEBAR_FILE"
        echo "  → Removed old sidebar injection."
    fi

    # Use Python to safely inject JS (avoids all sed/escaping issues)
    python3 << 'PYEOF'
import sys

sidebar_file = "/usr/local/CyberCP/baseTemplate/templates/baseTemplate/index.html"
marker_start = "<!-- SecuritySuite Menu Start -->"
marker_end = "<!-- SecuritySuite Menu End -->"

js_block = """
<!-- SecuritySuite Menu Start -->
<script>
(function() {
    'use strict';
    function injectSecuritySuiteMenu() {
        if (document.getElementById('ss-sidebar-link')) return true;
        
        // CyberPanel 2.4.4+ uses id="security-submenu"
        var subMenu = document.getElementById('security-submenu');
        
        if (!subMenu) {
            // Fallback for older versions: find 'Security' link
            var allLinks = document.querySelectorAll('a');
            var securityParent = null;
            for (var i = 0; i < allLinks.length; i++) {
                var linkText = (allLinks[i].textContent || '').trim();
                if (linkText === 'Security') {
                    securityParent = allLinks[i].closest('li');
                    break;
                }
            }
            if (!securityParent) return false;
            subMenu = securityParent.querySelector('ul');
        }
        
        if (!subMenu) return false;
        
        // Check if we already injected in this submenu (double check)
        if (subMenu.querySelector('#ss-sidebar-link')) return true;

        var li = document.createElement('a'); // Note: In v2.4.4 items are <a>, older versions used <li><a></a>
        
        // If it's the new CyberPanel 2.4.4 format (div > a.menu-item)
        if (subMenu.tagName.toLowerCase() === 'div') {
            li.href = '/securitysuite/';
            li.target = '_blank';
            li.className = 'menu-item';
            li.id = 'ss-sidebar-link';
            li.innerHTML = '<span><i class="fa fa-shield" style="margin-right:5px;color:#3b82f6;"></i> Security Suite</span>';
            if (window.location.pathname.indexOf('/securitysuite') === 0) {
                li.classList.add('active');
            }
            subMenu.appendChild(li);
        } else {
            // Older format (ul > li > a)
            var wrapperLI = document.createElement('li');
            wrapperLI.id = 'ss-sidebar-link';
            li.href = '/securitysuite/';
            li.target = '_blank';
            li.style.cssText = 'cursor:pointer;';
            li.innerHTML = '<i class="fa fa-shield" style="margin-right:5px;color:#3b82f6;"></i> Security Suite';
            if (window.location.pathname.indexOf('/securitysuite') === 0) {
                li.style.color = '#3b82f6';
                li.style.fontWeight = '600';
            }
            wrapperLI.appendChild(li);
            subMenu.appendChild(wrapperLI);
        }
        
        return true;
    }
    var attempts = 0;
    var timer = setInterval(function() {
        attempts++;
        if (injectSecuritySuiteMenu() || attempts >= 40) clearInterval(timer);
    }, 500);
    window.addEventListener('hashchange', function() { setTimeout(injectSecuritySuiteMenu, 500); });
})();
</script>
<!-- SecuritySuite Menu End -->
"""

try:
    with open(sidebar_file, 'r') as f:
        content = f.read()

    # Remove any existing injection
    if marker_start in content:
        start = content.index(marker_start)
        end = content.index(marker_end) + len(marker_end)
        content = content[:start] + content[end:]

    # Inject before </body>
    if '</body>' in content:
        content = content.replace('</body>', js_block + '\n</body>')
        print("  OK: Injected before </body>")
    elif '</html>' in content:
        content = content.replace('</html>', js_block + '\n</html>')
        print("  OK: Injected before </html>")
    else:
        content += js_block
        print("  OK: Appended to file")

    with open(sidebar_file, 'w') as f:
        f.write(content)

except Exception as e:
    print(f"  ERROR: {e}", file=sys.stderr)
    sys.exit(1)
PYEOF

    if grep -q "$SIDEBAR_MARKER_START" "$SIDEBAR_FILE"; then
        echo "  ✓ Security Suite menu injected into CyberPanel sidebar."
    else
        echo "  ⚠ Could not inject sidebar. Access directly: /securitysuite/"
    fi
else
    echo "  ⚠ Sidebar template not found. Access directly: /securitysuite/"
fi

# ── Restart service ──────────────────────────────────────────────────────
echo "→ Restarting LiteSpeed (lscpd)…"
if systemctl is-active --quiet lscpd; then
    systemctl restart lscpd
    echo "  ✓ lscpd restarted."
else
    echo "  ⚠ lscpd not found. Restart manually."
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ✓ Installation Complete!                                ║"
echo "║  CyberPanel Security Suite v1.7                          ║"
echo "║                                                          ║"
echo "║  Plugin:   $PLUGIN_DIR"
echo "║  Logs:     $LOG_FILE"
echo "║  Fail2ban: $(systemctl is-active fail2ban 2>/dev/null || echo 'unknown')"
echo "║                                                          ║"
echo "║  CyberPanel → Security → Security Suite                  ║"
echo "╚══════════════════════════════════════════════════════════╝"
